config/routes.rb
Rails.application.routes.draw do
  # Default URL Options
  default_url_options :host => 'localhost', port: 3000 unless Rails.env.production?
  default_url_options :host => 'linkedin-scraper.up.railway.app' if Rails.env.production?

  ## Root Path
  root 'main#index'
  ## Scrape
  post 'scrape', to: 'main#scrape', as: 'scrape'

  ## Search Profiles
  post 'search_profiles', to: 'main#search_profiles', as: 'search_profiles'

  ## Search Collaborations
  post 'search_collaborations', to: 'main#search_collaborations', as: 'search_collaborations'

  ## Embed
  post 'embed', to: 'main#embed', as: 'embed'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  scope :today, -> { where(created_at: Time.current.beginning_of_day.in_time_zone(Time.zone)..Time.current.end_of_day.in_time_zone(Time.zone)) }
  scope :this_week, -> { where(created_at: Time.current.beginning_of_week.in_time_zone(Time.zone)..Time.current.end_of_week.in_time_zone(Time.zone)) }
  scope :this_month, -> { where(created_at: Time.current.beginning_of_month.in_time_zone(Time.zone)..Time.current.end_of_month.in_time_zone(Time.zone)) }
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_neighbors :embedding

  validates :username, uniqueness: true
  before_save :classify

  def refresh
    updated_data = LinkedInService.call(username)

    version = Profiles::ScraperService::VERSIONS[:document]
    updated_document = Profiles::ScraperService.call(username, version, updated_data).strip.gsub("\n", ' ')

    updated_embedding = OpenAI::EmbeddingService.call(updated_document)

    update!(metadata: updated_data, document: updated_document, embedding: updated_embedding)
  end

  def classify(overwrite = false)
    if overwrite || classification.blank?
      self.classification = Profiles::ClassifierService.call(document)
    end
  end
end

app/models/query.rb
class Query < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  ## Sessions
  # Clear Session Data
  def clear_session
    session.clear
  end

  # Create Do-Not-Track Session
  def do_not_track
    session[:do_not_track] = true unless session[:do_not_track]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  ## GET /
  def index; end

  ## POST /scrape
  def scrape
    username = params[:username]

    if username.present?
      ## Perform scraping in background
      ProfileScrapeWorker.perform_async(username)

      redirect_to root_path, notice: "#{username} will be added to the database in the background."
    else
      redirect_to root_path, notice: 'Invalid username, please try again.'
    end
  end

  ## POST /embed
  def embed
    input = params[:input]

    render json: {
             embedding: input.present? ? OpenAI::EmbeddingService.call(input) : nil
           }, status: :ok
  end

  ## POST /search_profiles
  def search_profiles
    input = params[:input]

    results = Profiles::SearchService.call(input)

    render json: { results: results }, status: :ok
  end

  ## POST /search_collaborations
  def search_collaborations
    input = params[:input]

    results = Collaborations::SearchService.call(input)
    recommendations = Collaborations::RecommendationService.call(input, results)
    email = Collaborations::EmailComposerService.call(input, recommendations)

    render json: { results: results, recommendations: recommendations, email_draft: email }, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Title -->
    <title><%= content_for?(:title) ? yield(:title) : 'LinkedIn Scraper' %></title>

    <!-- Viewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- CSRF and CSP Meta Tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Generic Meta Tags -->
    <meta name="keywords" content="linkedin, scraper, lazy, juan, ai, internal, tool">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : '' %>">
    
    <!-- Open Graph -->
    <meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'LinkedIn Scraper' %>">
    <meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : '' %>"/>
    <meta property="og:type" content='website'/>
    <meta property="og:url" content='<%= request.original_url %>'/>
    
    <!-- Manifest -->
    <link rel="manifest" href="/manifest.json">

    <!-- Stylesheets -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/fontawesome/web/css/all.css', media: 'all', 'data-turbolinks-track' => 'reload' %>

    <!-- Javascript -->
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Alerts -->
    <%= render 'components/alerts' %>
    
    <!-- Content -->
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!-- Landing Page -->
<div id="landing-page" class="page">
  <main>
    <div id="forms">
      <%= form_tag(scrape_path, method: :post) do %>
        <%= text_field_tag :username, nil, placeholder: "Enter username" %>
        <%= submit_tag "Scrape", class: "cta" %>
      <% end %>

      <%= form_tag(embed_path, method: :post) do %>
        <%= text_area_tag :input, nil, placeholder: "Enter text", rows: 5 %>
        <%= submit_tag "Embed", class: "cta" %>
      <% end %>

      <%= form_tag(search_profiles_path, method: :post) do %>
        <%= text_area_tag :input, nil, placeholder: "Enter description or keywords", rows: 5 %>
        <%= submit_tag "Search Profiles", class: "cta" %>
      <% end %>

      <%= form_tag(search_collaborations_path, method: :post) do %>
        <%= text_area_tag :input, nil, placeholder: "Enter project or campaign idea", rows: 5 %>
        <%= submit_tag "Search Collaborations", class: "cta" %>
      <% end %>
    </div>
  </main>
</div>